### ISSUE TITLE
Error No permission to call sandboxed `thread_send_message(_7532,_7534,_7536)'

### ISSUE THREAD

**Issue by avtaylor** [SWI-Prolog/pengines#26]
Hello.
This initiative is very good but I cannot run some of the apps. 
The error above is when I run the expert_system example.
Can this error be dealt with?
Thank you

**Comment by JanWielemaker** [comment]
See _Help/Limitations_ and _Help/Caveats_.   You cannot call `thread_send_message` because message passing is what makes all tasks in SWISH cooperate.   If you could find out about threads and send them messages you can easily interfere with other users.

Possibly this is an indirect consequence of using some higher level library predicate.  In that case report that, but in general we will not allow for the concurrency predicates to avoid overloading the server.

You can run a local copy in which you disable sandboxing.

**Comment by JanWielemaker** [comment]
See https://github.com/SWI-Prolog/swish#running-swish-without-sandbox-limitations
